compile: null
data:
  drop_last: true
  instance_filter:
    repetition_max_count: 32
    repetition_max_period: 13
    repetition_min_period: 1
  num_workers: 32
  pad_direction: right
  paths:
  - /shared/share_mala/hc3295/olmo/data/dummy2/part-000-00000.npy
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 8
  timeout: 0
ddp:
  find_unused_params: false
  grad_sync_mode: batch
device_eval_batch_size: ${device_train_microbatch_size}
device_train_microbatch_size: 16
distributed_strategy: ddp
dry_run: false
eval_interval: 10
eval_subset_num_batches: -1
evaluators:
- label: arc_easy
  type: downstream
gen1_gc_interval: 1
global_train_batch_size: 1024
load_path: null
max_duration: 1ep
max_grad_norm: 1.0
max_grad_norm_ratio: null
model:
  activation_type: swiglu
  alibi: false
  attention_dropout: 0.0
  attention_layer_norm: false
  attention_layer_norm_with_affine: false
  bias_for_layer_norm: false
  block_type: sequential
  clip_qkv: null
  d_model: 256
  embedding_dropout: 0.0
  embedding_size: 50304
  eos_token_id: 0
  flash_attention: true
  include_bias: false
  init_cutoff_factor: 3
  init_device: cuda
  init_fn: normal
  init_std: 0.02
  layer_norm_eps: 1e-6
  layer_norm_type: rms
  layer_norm_with_affine: true
  max_sequence_length: 4096
  mlp_ratio: 8
  n_heads: 8
  n_layers: 8
  pad_token_id: 1
  residual_dropout: 0.0
  rope: true
  vocab_size: 50280
  weight_tying: false
optimizer:
  betas:
  - 0.9
  - 0.95
  decay_embeddings: true
  decay_norm_and_bias: true
  eps: 1e-8
  learning_rate: 0.0006
  metrics_log_interval: 10
  name: adamw
  weight_decay: 0.1
precision: amp_bf16
run_name: OLMo-20M_dummy10.35-dummy20.65_20241126_231907
save_folder: workspace/${run_name}
save_interval_unsharded: 10
save_num_unsharded_checkpoints_to_keep: -1
save_overwrite: false
scheduler:
  alpha_f: 0.1
  name: cosine_with_warmup
  t_warmup: 5000
  warmup_min_lr: 0
seed: 6198
speed_monitor:
  window_size: 20
stop_at: 406934
tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right
